//
//  CategoriesOfInterest.swift
//  Chatter
//
//  Created by Matthias Schrock on 5/3/23.
//

struct Category: Hashable, Codable {
    let categoryTitle: String
    let categoryItems: [String]
}

let categoriesOfInterest: [Category] = [
    Category(categoryTitle: "Music", categoryItems: music),
    Category(categoryTitle: "Food", categoryItems: food),
    Category(categoryTitle: "Film", categoryItems: moviesAndTV),
    Category(categoryTitle: "Sports", categoryItems: sports)
]

let music: [String] = [
    "Pop",
    "Hip Hop/Rap",
    "Rock",
    "Country",
    "R&B/Soul",
    "Christian/Gospel",
    "EDM",
    "Alternative/Indie",
    "Metal",
    "Reggae",
    "Jazz",
    "Blues",
    "Classical",
    "Folk",
    "Punk",
    "Latin",
    "Gospel",
    "Funk",
    "Americana",
    "World",
    "New Age",
    "Ambient",
    "Experimental",
    "Children's",
    "Soundtrack",
    "Comedy",
    "Holiday",
    "J-Pop/K-Pop",
    "Acoustic",
    "Electronic",
    "Dance",
    "Heavy Metal",
    "Thrash Metal",
    "Grunge",
    "Hard Rock",
    "Instrumental",
    "Industrial"
]

let food: [String] = [
    "American",
    "Italian",
    "Mexican",
    "Chinese",
    "Japanese",
    "Indian",
    "Thai",
    "Greek",
    "French",
    "Mediterranean",
    "Korean",
    "Spanish",
    "Vietnamese",
    "Middle Eastern",
    "Caribbean",
    "Cajun/Creole",
    "Southern",
    "Tex-Mex",
    "German",
    "Ethiopian",
    "Brazilian",
    "Peruvian",
    "Russian",
    "Scandinavian",
    "Jewish",
    "Irish",
    "British",
    "Australian",
    "African",
    "Central American",
    "South American",
    "Filipino",
    "Malaysian",
    "Indonesian",
    "Taiwanese",
    "Hong Kong-style"
]

let moviesAndTV: [String] = [
    "Avengers: Endgame",
    "Game of Thrones",
    "Star Wars",
    "Breaking Bad",
    "The Office (US)",
    "Titanic",
    "Friends",
    "Jurassic World",
    "The Dark Knight",
    "Stranger Things",
    "Black Panther",
    "The Crown",
    "The Lion King",
    "The Wizard of Oz",
    "Forrest Gump",
    "Gone with the Wind",
    "The Godfather",
    "Casablanca",
    "The Walking Dead",
    "The Big Bang Theory",
    "E.T.",
    "Cheers",
    "The Shawshank Redemption",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "Indiana Jones",
    "The Sopranos",
    "Rocky",
    "Back to the Future",
    "The Wire",
    "Jaws",
    "The Simpsons",
    "The Twilight Zone",
    "Star Trek",
    "The West Wing",
    "Mad Men",
    "The X-Files",
    "MAS*H",
    "Seinfeld",
    "The Sound of Music"
]

let sports: [String] = [
    "American Football",
    "Basketball",
    "Baseball",
    "Ice Hockey",
    "Soccer",
    "Tennis",
    "Golf",
    "Boxing",
    "Martial Arts",
    "Auto Racing",
    "Wrestling",
    "Volleyball",
    "Rugby",
    "Cycling",
    "Gymnastics",
    "Track and Field",
    "Swimming",
    "Skiing",
    "Snowboarding",
    "Figure Skating",
    "Skateboarding",
    "Surfing",
    "Lacrosse",
    "Field Hockey",
    "Cricket",
    "Ultimate Frisbee",
    "Table Tennis",
    "Badminton",
    "Billiards",
    "Archery",
    "Horse Racing",
    "Fishing",
    "Hunting",
    "Shooting",
    "Fencing",
    "CrossFit",
    "Powerlifting",
    "Weightlifting",
    "Strongman",
    "Rowing"
]
